import { environment } from '../environment';
import axiosInstance from './axiosConfig';

class ProfileService {
    private apiUrl: string;

    constructor() {
        this.apiUrl = `${environment.apiUrl}/api/Profile`;

    }

    async create(profile: ProfileFullViewModel): Promise<string> {
        try {
            console.log("profile", profile);
            const response = await axiosInstance.post<string>(`${this.apiUrl}/`, profile);
            console.log('Profile creation response:', response);
            if (!response.data) {
                throw new Error('No profile ID returned from server');
            }
            return response.data;
        } catch (error: any) {
            console.error('Error creating profile:', {
                error: error,
                response: error.response?.data,
                status: error.response?.status,
                fullError: error.message
            });
            throw error;
        }
    }

    async createClientProfile(clientData: CreateClientProfileDto): Promise<string> {
        try {
            // Convert the client data to the full profile format
            const profile: ProfileFullViewModel = {
                id: '', // Will be generated by the server
                image: null,
                name: `${clientData.firstName} ${clientData.lastName}`,
                dateOfBirth: null,
                gender: null,
                location: null,
                email: clientData.email,
                phoneNumber: clientData.tel,
                userType: UserType.Client,
                about: null,
                newPassword: null,
                userId: clientData.userId,
                height: null,
                weight: null,
                bmi: null
            };

            console.log("Creating client profile:", profile);
            const response = await axiosInstance.post<string>(`${this.apiUrl}/`, profile);
            console.log('Client profile creation response:', response);
            
            if (!response.data) {
                throw new Error('No profile ID returned from server');
            }
            return response.data;
        } catch (error: any) {
            console.error('Error creating client profile:', {
                error: error,
                response: error.response?.data,
                status: error.response?.status,
                fullError: error.message
            });
            throw error;
        }
    }

    async update(id: string, profile: ProfileFullViewModel): Promise<void> {
        try {
            await axiosInstance.put<ProfileFullViewModel>(`${this.apiUrl}/${id}`, profile);
        } catch (error: any) {
            console.error('Error updating profile:', error.response?.data || error.message);
            throw error;
        }
    }

    async updateExtendedInfo(userId: string, extendedInfo: ExtendedProfileInfo): Promise<void> {
        try {
            // First get the current profile
            const currentProfile = await this.getByUserId(userId);
            if (!currentProfile) {
                throw new Error('Profile not found');
            }

            // Update the profile with extended information
            const updatedProfile: ProfileFullViewModel = {
                ...currentProfile,
                height: extendedInfo.height,
                weight: extendedInfo.weight,
                gender: extendedInfo.gender || currentProfile.gender,
                bmi: null // Will be calculated by the API
            };

            await this.update(currentProfile.id, updatedProfile);
        } catch (error: any) {
            console.error('Error updating extended profile info:', error.response?.data || error.message);
            throw error;
        }
    }
    

    async getAll(): Promise<ProfileListViewModel[]> {
        try {
            const response = await axiosInstance.get<ProfileListViewModel[]>(`${this.apiUrl}/`);
            return response.data;
        } catch (error: any) {
            console.error('Login failed:', error.response?.data || error.message);
            return [];
        }
    }

    async getById(id: string): Promise<ProfileFullViewModel | null> {
        try {
            const response = await axiosInstance.get<ProfileFullViewModel>(`${this.apiUrl}/${id}`);
            console.log("response", response.data);
            return response.data;
        } catch (error: any) {
            console.error('Error fetching profile:', error.response?.data || error.message);
            return null;
        }
    }

    async getByUserId(id: string): Promise<ProfileFullViewModel | null> {
        try {
            const response = await axiosInstance.get<ProfileFullViewModel>(`${this.apiUrl}/user/${id}`);
            return response.data;
        } catch (error: any) {
            console.error('Error fetching profile:', error.response?.data || error.message);
            return null;
        }
    }

    async getExternalClients(): Promise<ProfileListViewModel[]> {
        try {
            // First get all clients
            const clients = await this.getAll();
            // Then filter out the clients that are not external
            const externalClients = clients.filter((client) => client.userType === UserType.ExternalClient);
            return externalClients;
        } catch (error: any) {
            console.error('Error fetching external clients:', error.response?.data || error.message);
            return [];
        }
    }
}

export default new ProfileService();

export interface ProfileListViewModel {
  id: string;
  email: string;
  firstName: string;    
  lastName: string;
  userType: UserType;
}

export interface ProfileFullViewModel {
    id: string;
    image: string | null;
    name: string | null;
    dateOfBirth: Date | null;
    gender: string | null;
    location: string | null;
    email: string | null;
    phoneNumber: string | null;
    userType: UserType;
    about: string | null;
    newPassword: string | null;
    userId: string;
    height: number | null; // Height in centimeters
    weight: number | null; // Weight in kilograms
    bmi: number | null; // Calculated BMI (read-only)
}

export interface CreateClientProfileDto {
    userId: string;
    firstName: string;
    lastName: string;
    email: string;
    tel: string;
}

export interface ExtendedProfileInfo {
    height: number | null; // Height in centimeters
    weight: number | null; // Weight in kilograms
    gender: string | null; // 'Male', 'Female', 'Other', or null
}

export enum UserType {
    Admin,
    Trainer,
    Client,
    ExternalClient
} 